---

- name: wait for stopped instance for '{{ instance.ami_shortname }}' AMI
  ec2_instance_facts:
    filters:
      instance-state-name: ['stopped']
      'tag:Name':        '{{ instance.hostname }}'
      'tag:Environment': 'ami'
      'tag:Function':    '{{ instance.function }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_ec2_ami_instance_facts
  until: >
    ("instances" in _aws_ec2_ami_instance_facts) and
    (_aws_ec2_ami_instance_facts.instances | length == 1)
  retries: 720
  delay: 15

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      found stopped temporary instance for AMI <b>{{ instance.ami_shortname }}</b>
  when: notifier_role is defined

- name: refresh assumed role credentials
  include_role:
    name: aws-iam-assume-role

- name: create AMI
  ec2_ami:
    description: '{{ instance.ami_description }}'
    instance_id: '{{ _aws_ec2_ami_instance_facts.instances.0.instance_id }}'
    name: '{{ instance.ami_name }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    state: present
    tags:
      Short Name: '{{ instance.ami_shortname }}'
      Source AMI ID: '{{ instance.image }}'
      To Encrypt: '{{ ("True" if instance.ami_kms_key_alias else "False") }}'
      KMS Key Alias: '{{ instance.ami_kms_key_alias | default(None) }}'
  register: _aws_ec2_ami_create

- name: save unencrypted AMI creation data
  set_fact:
    _aws_ec2_ami_unencrypted_amis: >-
      {{ _aws_ec2_ami_unencrypted_amis
         | default([])
         | union([_aws_ec2_ami_create]) }}

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: started creating AMI <b>{{ instance.ami_shortname }}</b>
  when: notifier_role is defined
